name: Update Frontend on Strapi API Change
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Strapi API for Changes
      run: |
        for api in "http://83.166.147.249:1337/api/accueil?populate=*" "http://83.166.147.249:1337/api/articles?populate=*" "http://83.166.147.249:1337/api/evenements?populate=*"; do
          api_name=$(echo $api | awk -F '/' '{print $NF}')
          curl -s $api > current_response_$api_name.json
          if [ $? -eq 0 ]; then
            if diff -q current_response_$api_name.json previous_response_$api_name.json > /dev/null; then
              echo "No changes in the $api_name API. Skipping workflow execution."
            else
              echo "Changes detected in the $api_name API. Updating frontend..."
              git config --local user.email "actions@github.com"
              git config --local user.name "GitHub Actions"
              git add .
              git commit -m "Update frontend on $api_name API change"
              git push --quiet --set-upstream origin ${{ github.head_ref }}
              mv current_response_$api_name.json previous_response_$api_name.json
            fi
          else
            echo "Error: Unable to fetch $api_name API data."
            exit 1
          fi
        done
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
