name: Update Frontend on Strapi API Change
on:
  schedule:
    - cron: "*/.1 * * * *"

jobs:
  update-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Strapi API for Changes
      run: |
        curl -s http://83.166.147.249:1337/api/accueil?populate=* > current_response.json
        if [ $? -eq 0 ]; then
          if diff -q current_response.json previous_response.json > /dev/null; then
            echo "No changes in the Strapi API. Skipping workflow execution."
            exit 0
          else
            echo "Changes detected in the Strapi API. Updating frontend..."
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .
            git commit -m "Update frontend on Strapi API change"
            git push --quiet --set-upstream origin ${{ github.head_ref }}
            mv current_response.json previous_response.json
          fi
        else
          echo "Error: Unable to fetch Strapi API data."
          exit 1
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
