name: Update Frontend on Strapi API Change
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-frontend:
    runs-on: ubuntu-latest

    needs: []

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Strapi API for Changes
      run: |
        curl -s http://83.166.147.249:1337/api/accueil?populate=* > current_response.json
        if diff -q current_response.json previous_response.json > /dev/null; then
          echo "No changes in the Strapi API."
          exit 0
        else
          echo "Changes detected in the Strapi API. Updating frontend..."
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update frontend on Strapi API change"
          git push --quiet --set-upstream origin ${{ github.head_ref }}
        fi
        mv current_response.json previous_response.json
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

# Explicitly state that Java is not needed
java: false
